local _constants = require('ouest_freestyle_station.constants')
-- local constructionutil = require "constructionutil"
local moduleHelpers = require('ouest_freestyle_station.moduleHelpers')
-- local modulesutil = require "modulesutil"
local transfUtils = require('ouest_freestyle_station.transfUtils')
local transfUtilsUG = require "transf"


function data()

return {
	availability = {
		yearFrom = -1,
		yearTo = -1
	},
	category = { },
	cost = {
		price = 0,
	},
	description = {
		name = '',
		description = '',
		icon = "ui/empty.tga"
	},
	metadata = { },
	order = {
		value = 1,
	},
	type = _constants.trackElectrificationModuleType,
	updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
		-- print('trackElectrificationYes.module.updateFn ending')
		-- result.models[#result.models + 1] = {
		-- 	id = _constants.emptyModelFileName,
		-- 	slotId = slotId,
		-- 	transf = slotTransf,
		-- 	tag = tag
		-- }
	end,

	getModelsFn = function(params)
		return {
			-- {
			-- 	id = _constants.emptyModelFileName,
			-- 	transf = _constants.idTransf,
			-- },
		}
	end
}

end
