local _constants = require('ouest_freestyle_station.constants')
local moduleHelpers = require('ouest_freestyle_station.moduleHelpers')


function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        category = {
            categories = { "passenger-road-access-axial", },
        },
        cost = {
            price = 0,
        },
        description = {
            name = _("AxialPassengerStairsEdgeName"),
            --description = _("AxialPassengerStairsEdgeDesc"),
            icon = "ui/exitWithEdge2m.tga"
        },
        metadata = { },
        order = {
            value = 11,
        },
        type = _constants.axialPassengerEdgeModuleType,
        updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
            return moduleHelpers.axialAreas.exitWithEdgeModule_updateFn(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams, false)
        end,

        getModelsFn = function(params)
            return {
                {
                    id = 'open_stairs/bridge_chunk_2m.mdl',
                    transf = _constants.idTransf,
                },
                moduleHelpers.axialAreas.getPreviewIcon(params)
            }
        end
    }
end
