local _constants = require('ouest_freestyle_station.constants')
local moduleHelpers = require('ouest_freestyle_station.moduleHelpers')
local transfUtils = require('ouest_freestyle_station.transfUtils')

-- LOLLO NOTE we need this to avoid the street edges trying to snap to each other while configuring.
-- After build 35716, non-snappy edges will throw collision when they are connected to the road network and the user opens the config menu,
-- so we force all edges to snappy.
function data()
    return {
        availability = {
            yearFrom = -1,
            yearTo = -1,
        },
        category = {
            categories = { "passenger-road-access-stairs", },
        },
        cost = {
            price = 0,
        },
        description = {
            name = _("OpenStairsExitWithSnappyEdgeName_2m"),
            --description = _("OpenStairsExitWithSnappyEdgeDesc"),
            icon = "ui/exitWithSnappyEdge2m.tga"
        },
        metadata = { },
        order = {
            value = 61,
        },
        type = _constants.openStairsExitModuleType,
        updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
            return moduleHelpers.openStairs.stairsExitWithEdgeModule_v2_updateFn(
                    result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams, false, true
            )
        end,

        getModelsFn = function(params)
            return {
                {
                    -- id = 'lollo_freestyle_train_station/open_stairs/era_c_bridge_chunk_4m.mdl',
                    id = 'open_stairs/bridge_chunk_2m.mdl',
                    transf = _constants.idTransf,
                },
                moduleHelpers.openStairs.getPreviewIcon(params),
            }
        end
    }
end
