local _constants = require('ouest_freestyle_station.constants')
local moduleHelpers = require('ouest_freestyle_station.moduleHelpers')

-- LOLLO NOTE after build 35716, we need this to avoid the station throwing collisions whenever an external edge is connected.
-- It is inconvenient to place, so we hide it and replace it quietly.
function data()
    return {
        availability = {
            yearFrom = -1,
            yearTo = -1,
        },
        category = {
            categories = { "passenger-road-access-stairs", },
        },
        cost = {
            price = 0,
        },
        description = {
            name = _("OpenStairsExitWithSnappyEdgeName_2m"),
            --description = _("OpenStairsExitWithSnappyEdgeDesc"),
            icon = "ui/exitWithSnappyEdge2m.tga"
        },
        metadata = { },
        order = {
            value = 61,
        },
        type = _constants.openStairsExitModuleType,
        updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
            return moduleHelpers.openStairs.stairsExitWithEdgeModule_v2_updateFn(
                    result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams, true, false
            )
        end,

        getModelsFn = function(params)
            return {
                {
                    -- id = 'lollo_freestyle_train_station/open_stairs/era_c_bridge_chunk_4m.mdl',
                    id = 'open_stairs/bridge_chunk_2m.mdl',
                    transf = _constants.idTransf,
                },
                moduleHelpers.openStairs.getPreviewIcon(params),
            }
        end
    }
end
