local _constants = require('ouest_freestyle_station.constants')
local moduleHelpers = require('ouest_freestyle_station.moduleHelpers')


function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        category = {
            categories = { "passenger-road-access", },
        },
        cost = {
            price = 0,
        },
        description = {
            name = _("FlatPassengerStairsEdgeName"),
            -- description = _("FlatPassengerStairsEdgeDesc"),
            icon = "ui/exitWithEdge2m.tga"
        },
        metadata = { },
        order = {
            value = 10,
        },
        type = _constants.flatPassengerEdgeModuleType,
        updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
            return moduleHelpers.flatAreas.exitWithEdgeModule_updateFn(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams, false)
        end,

        getModelsFn = function(params)
            return {
                {
                    id = 'open_stairs/bridge_chunk_2m.mdl',
                    transf = _constants.idTransf,
                },
                moduleHelpers.flatAreas.getPreviewIcon(params),
            }
        end
    }
end
