local constants = require('ouest_train_station.constants')

function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        category = {
            categories = { "platform-era-height-style", },
        },
        cost = {
            price = 0,
        },
        description = {
            name = _("PlatformHeight92Name"),
            description = _("PlatformHeight92Desc"),
            icon = "ui/ouest_train_station/platformHeight92.tga"
        },
        metadata = { },
        order = {
            value = 47,
        },
        type = constants.platformHeightModuleType,
        updateFn = function(result, slotTransf, tag, slotId, addModelFn, params, updateScriptParams)
            -- local nTerminal, nTrackEdge, baseId = result.demangleId(slotId)
            -- if not nTerminal or not baseId then return end

            -- result.models[#result.models + 1] = {
            -- 	id = 'lollo_freestyle_train_station/icon/lilac.mdl',
            -- 	slotId = slotId,
            -- 	transf = slotTransf,
            -- 	tag = tag
            -- }
        end,

        getModelsFn = function(params)
            return {
                {
                    id = 'icon/height.mdl',
                    transf = constants.idTransf,
                }
            }
        end
    }
end